# win_yolo_tcp_sender_botsort_threat.py

## Purpose

This file is the main entry point of the Windows AI application.

It implements the complete perception pipeline by acquiring video frames, performing object detection, tracking detected objects, evaluating their threat level and transmitting the resulting information to the Ubuntu ROS 2 environment.

All processing is performed sequentially for every incoming frame, making this file the central component of the AI subsystem.

---

## Responsibilities

The application performs the following tasks:

- Initialize the AI environment.
- Load the trained YOLO model.
- Connect to the video source.
- Execute object detection.
- Track detected objects.
- Evaluate threat levels.
- Serialize detection data.
- Transmit results through TCP.
- Display the processed video stream.

The output generated by this application forms the primary perception input for the entire robotic system.
