train: ../../../datasets/01_btr_original_1class/train/images
val: ../../../datasets/01_btr_original_1class/valid/images
test: ../../../datasets/01_btr_original_1class/test/images

nc: 1
names:
  0: BTR
