train: ../../../datasets/03_roboflow_military_footage_8class/train/images
val: ../../../datasets/03_roboflow_military_footage_8class/valid/images
test: ../../../datasets/03_roboflow_military_footage_8class/test/images

nc: 8
names:
  0: artillery
  1: car
  2: explosion
  3: military_truck
  4: military_vehicle
  5: person
  6: tank
  7: truck
