train: ../../../datasets/04_roboflow_tank_2class/train/images
val: ../../../datasets/04_roboflow_tank_2class/valid/images
test: ../../../datasets/04_roboflow_tank_2class/test/images

nc: 2
names:
  0: unknown
  1: military_vehicle
