train: ../../../datasets/05_amad5_aerial_military_5class_clean/train/images
val: ../../../datasets/05_amad5_aerial_military_5class_clean/val/images
test: ../../../datasets/05_amad5_aerial_military_5class_clean/test/images

nc: 5
names:
  0: military_tank
  1: military_vehicle
  2: civilian
  3: soldier
  4: civilian_vehicle
